version: "3.4"

services:
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/src
            - ./local.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: .
        command: ["./start-php-fpm.sh"]
        depends_on:
            - mysql
            - redis
        volumes:
            - ./app:/src/app
            - ./config:/src/config
            - ./database:/src/database
            - ./resources:/src/resources
            - ./routes:/src/routes
            - ./storage:/src/storage
            - ./tests:/src/tests
            - ./composer.json:/src/composer.json
            - ./composer.lock:/src/composer.lock
            - ./.env:/src/.env
            - ./.env.example:/src/.env.example
            - ./start-php-fpm.sh:/src/start-php-fpm.sh
            - ./phpunit.xml:/src/phpunit.xml
            - ./ruleset.xml:/src/ruleset.xml
        environment:
            COMPOSER_MEMORY_LIMIT: 4G
    mysql:
        image: "mysql:latest"
        ports:
            - "33061:3306"
        volumes:
            - ./mysql:/etc/mysql/conf.d
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: supersecret
    redis:
        image: redis:latest
